default_options: &default_options
  :w:               1
  :pool_size:       5
  :pool_timeout:    5
  :connect_timeout: 5
  :reconnect_attempts:          53
  :reconnect_retry_seconds:     0.1
  :reconnect_retry_multiplier:  2
  :reconnect_max_retry_seconds: 5

development: &development
  uri: mongodb://jgaviria:Sofia123!@ds061189.mongolab.com:61189/mongo_logger_db
  options:
    <<: *default_options

# Separate Working storage connection and database for testing
#development_working_storage: &development
#  uri: mongodb://127.0.0.1:27017/logging_development
#  options:
#    <<: *default_options

test:
  uri: mongodb://jgaviria:Sofia123!@ds061189.mongolab.com:61189/mongo_logger_db
  options:
    <<: *default_options



# Production Settings
production:
  uri: mongodb://jgaviria:Sofia123!@ds061189.mongolab.com:61189/mongo_logger_db

 options:
    <<: *default_options


